version: '3.9'

networks:
  t3_proxy:
    name: t3_proxy
    external: true

services:
  personal-website:
    image: ghcr.io/varadrane7/portfolio:${GIT_COMMIT_HASH:-latest}
    deploy:
      update_config:
        order: start-first
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.varad-portfolio-rtr.entrypoints=websecure"
      - "traefik.http.routers.varad-portfolio-rtr.rule=Host(`kurlaserver.nl`) || Host(`www.kurlaserver.nl`) || Host(`varadrane.com`) || Host(`www.varadrane.com`)"
      # Middlewares
      - "traefik.http.routers.varad-portfolio-rtr.middlewares=chain-no-auth@file"
