name: Build and Deploy Docker Stak

on:
  push:
    branches: ['master']
    # This means "trigger on any push to the main branch."
    # Merging a PR to main is effectively a push event on main.

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repo
      - name: Check out repository
        uses: actions/checkout@v4

      # 2) Set up QEMU for multi-arch support
      # This step is required for building images for non-native architectures (e.g., ARM).
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm, arm64

      # 3) Set up Docker Buildx (which uses the docker-container driver)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      # 4. Log in to GHCR using the default GITHUB_TOKEN
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build and push your image
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            --tag ghcr.io/varadrane7/portfolio:latest \
            --tag ghcr.io/varadrane7/portfolio:${{ github.sha }} \
            --push \
            .

  deploy-to-vps:
    runs-on: unbuntu-latest
    needs:
      - build-and-push-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
    
    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: varad-portfolio
        file: docker-stack.yaml
        host: 150.230.235.239
        user: deploy
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        env_file: ./envfile

